name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
    - 'backend/**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: backend action triggered
        run: echo Hello, world!
